/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.SkinnedMesh;
    Bone: THREE.Bone;
    Bone001: THREE.Bone;
    Bone0: THREE.Bone;
  };
  materials: {
    ["Material_46.002"]: THREE.MeshStandardMaterial;
  };
};

export function LeftHand(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/hand_left.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <skinnedMesh
          geometry={nodes.Object_5.geometry}
          material={materials["Material_46.002"]}
          skeleton={nodes.Object_5.skeleton}
        />
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone001} />
        <primitive object={nodes.Bone0} />
      </group>
    </group>
  );
}

useGLTF.preload("/hand_left.glb");
